os: windows
matrix:
  - language:
      - python: 3.6
    install:
      - pip install pyinstaller
    script:
      - cd GamingUI/htmls
      - pyinstaller --onefile web.py
  -  language:
      - go: 1.11
     install:
      - go get https://github.com/zserge/webview
