os: linux
language: 
  - go
  - c
compiler: gcc
sudo: required
dist: trusty
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
before_script:
  - go vet ./...
install:
  # Add Godeps dependencies to GOPATH and PATH
  - make get-deps
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
install:
      - go build -buildmode=c-archive cli.go
      - gcc -shared -pthread -o cli.dll cli.c cli.a -lWinMM -lntdll -lWS2_32
      - go get https://github.com/zserge/webview
      - go build ui.go
