os: windows
language: go
sudo: false
before_script:
  - go vet ./...
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
compiler:
      - gcc
install:
      - go build -buildmode=c-archive cli.go
      - gcc -shared -pthread -o cli.dll cli.c cli.a -lWinMM -lntdll -lWS2_32
      - go get https://github.com/zserge/webview
      - go build ui.go
